services:
  php-server:
    build: .
    container_name: php85_web
    ports:
      - "8080:80" # http://localhost:8080
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db
    networks:
      - dev-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    container_name: php85_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  db_data: